version: '3'
services:
  redis:
    image: redis:3.2
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis:/data
  mysql:
    image: mariadb:10.3
    restart: always
    environment:
      MYSQL_DATABASE: superset
      MYSQL_ROOT_PASSWORD: superset
      MYSQL_USER: superset
      MYSQL_PASSWORD: superset
  superset:
    image: apache/incubator-superset
    restart: always
    environment:
      MYSQL_DB: superset
      MYSQL_USER: superset
      MYSQL_ROOT_PASSWORD: superset
      MYSQL_PASSWORD: superset
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      REDIS_HOST: redis
      REDIS_PORT: 6379
      SUPERSET_ENV: local
    ports:
      - 8088:8088
    command: "tail -f /dev/null"
    depends_on:
      - mysql
      - redis
    volumes:
      - .:/home/work/incubator-superset
      - superset-node-modules:/home/work/incubator-superset/superset/assets/node_modules
volumes:
  redis:
    external: false
  superset-node-modules:
    external: false
