version: '3'
services:
  redis:
    image: redis:3.2
    restart: unless-stopped
    ports:
      - 6379:6379
      - 9000:9000
    volumes:
      - redis:/data
  mysql:
    image: mariadb:10.3
    restart: always
    environment:
      MYSQL_DATABASE: superset
      MYSQL_ROOT_PASSWORD: superset
      MYSQL_USER: superset
      MYSQL_PASSWORD: superset
  superset:
    image: qventus/superset:0.31.2
    restart: always
    environment:
      MYSQL_DB: superset
      MYSQL_USER: superset
      MYSQL_ROOT_PASSWORD: superset
      MYSQL_PASSWORD: superset
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      REDIS_HOST: redis
      REDIS_PORT: 6379
      # If using production, comment development volume below
      #SUPERSET_ENV: production
      SUPERSET_ENV: development
    ports:
      - 8088:8088
      - 25:25
    command: "tail -f /dev/null"
    depends_on:
      - mysql
      - redis
    volumes:
      # this is needed to communicate with the postgres and redis services
      - ./superset_config.py:/home/superset/superset/superset_config.py
      # this is needed for development, remove with SUPERSET_ENV=production
      - ../../superset:/home/superset/superset
volumes:
  redis:
    external: false
